# Generated by Django 4.1.6 on 2023-02-10 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("money_spent", models.DecimalField(decimal_places=2, max_digits=6)),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
