# Generated by Django 4.1.6 on 2023-02-14 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_alter_dailyexpense_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyexpense",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
